# Generated by Django 6.0.6 on 2026-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('News', 'News')], default='General', max_length=100),
        ),
    ]
